In [46]:
#importações e caminho
import pandas as pd

caminho_arquivo = "/content/PARTICIPANTES_2024.csv"
#leitura do csv
df = pd.read_csv(caminho_arquivo, sep=';', encoding='latin-1', low_memory=False)
print(df.columns.tolist())

['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ENSINO', 'IN_TREINEIRO', 'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 'Q001', 'Q002', 'Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022', 'Q023']

In [47]:
#informações gerais
print("Dimensões:", df.shape)
print("\nColunas:", df.columns.tolist())
print("\nTipos:", df.dtypes)
print("\n% de valores ausentes:")
print(df.isnull().mean().round(3) * 100)
print("\nEstatísticas descritivas (numéricas):")
print(df.describe())
print("\nPrimeiras 5 linhas:", df.head())

Dimensões: (4332944, 38)

Colunas: ['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ENSINO', 'IN_TREINEIRO', 'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 'Q001', 'Q002', 'Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022', 'Q023']

Tipos: NU_INSCRICAO            int64
NU_ANO                  int64
TP_FAIXA_ETARIA         int64
TP_SEXO                object
TP_ESTADO_CIVIL         int64
TP_COR_RACA             int64
TP_NACIONALIDADE        int64
TP_ST_CONCLUSAO         int64
TP_ANO_CONCLUIU         int64
TP_ENSINO             float64
IN_TREINEIRO            int64
CO_MUNICIPIO_PROVA      int64
NO_MUNICIPIO_PROVA     object
CO_UF_PROVA             int64
SG_UF_PROVA            object
Q001                   object
Q002                   object
Q003                   object
Q004                   object
Q005                    int64
Q006                   object
Q007                   object
Q008                   object
Q009                   object
Q010                   object
Q011                   object
Q012                   object
Q013                   object
Q014                   object
Q015                   object
Q016                   object
Q017                   object
Q018                   object
Q019                   object
Q020                   object
Q021                   object
Q022                   object
Q023                   object
dtype: object

% de valores ausentes:
NU_INSCRICAO           0.0
NU_ANO                 0.0
TP_FAIXA_ETARIA        0.0
TP_SEXO                0.0
TP_ESTADO_CIVIL        0.0
TP_COR_RACA            0.0
TP_NACIONALIDADE       0.0
TP_ST_CONCLUSAO        0.0
TP_ANO_CONCLUIU        0.0
TP_ENSINO             64.3
IN_TREINEIRO           0.0
CO_MUNICIPIO_PROVA     0.0
NO_MUNICIPIO_PROVA     0.0
CO_UF_PROVA            0.0
SG_UF_PROVA            0.0
Q001                   0.0
Q002                   0.0
Q003                   0.0
Q004                   0.0
Q005                   0.0
Q006                   0.0
Q007                   0.0
Q008                   0.0
Q009                   0.0
Q010                   0.0
Q011                   0.0
Q012                   0.0
Q013                   0.0
Q014                   0.0
Q015                   0.0
Q016                   0.0
Q017                   0.0
Q018                   0.0
Q019                   0.0
Q020                   0.0
Q021                   0.0
Q022                   0.0
Q023                   0.0
dtype: float64

Estatísticas descritivas (numéricas):
       NU_INSCRICAO     NU_ANO  TP_FAIXA_ETARIA  TP_ESTADO_CIVIL  \
count  4.332944e+06  4332944.0     4.332944e+06     4.332944e+06
mean   2.100643e+11     2024.0     4.803929e+00     1.034212e+00
std    1.279403e+06        0.0     3.825449e+00     4.085476e-01
min    2.100621e+11     2024.0     1.000000e+00     0.000000e+00
25%    2.100632e+11     2024.0     2.000000e+00     1.000000e+00
50%    2.100643e+11     2024.0     3.000000e+00     1.000000e+00
75%    2.100654e+11     2024.0     6.000000e+00     1.000000e+00
max    2.100665e+11     2024.0     2.000000e+01     4.000000e+00

        TP_COR_RACA  TP_NACIONALIDADE  TP_ST_CONCLUSAO  TP_ANO_CONCLUIU  \
count  4.332944e+06      4.332944e+06     4.332944e+06     4.332944e+06
mean   2.042669e+00      1.030515e+00     1.780171e+00     2.263291e+00
std    1.004142e+00      2.281566e-01     7.716867e-01     4.510310e+00
min    0.000000e+00      0.000000e+00     1.000000e+00     0.000000e+00
25%    1.000000e+00      1.000000e+00     1.000000e+00     0.000000e+00
50%    2.000000e+00      1.000000e+00     2.000000e+00     0.000000e+00
75%    3.000000e+00      1.000000e+00     2.000000e+00     2.000000e+00
max    5.000000e+00      4.000000e+00     4.000000e+00     1.800000e+01

          TP_ENSINO  IN_TREINEIRO  CO_MUNICIPIO_PROVA   CO_UF_PROVA  \
count  1.545882e+06  4.332944e+06        4.332944e+06  4.332944e+06
mean   1.006213e+00  1.948465e-01        3.107075e+06  3.092511e+01
std    7.857914e-02  3.960825e-01        9.974972e+05  9.946173e+00
min    1.000000e+00  0.000000e+00        1.100015e+06  1.100000e+01
25%    1.000000e+00  0.000000e+00        2.408102e+06  2.400000e+01
50%    1.000000e+00  0.000000e+00        3.120904e+06  3.100000e+01
75%    1.000000e+00  0.000000e+00        3.550308e+06  3.500000e+01
max    2.000000e+00  1.000000e+00        5.300108e+06  5.300000e+01

               Q005
count  4.332944e+06
mean   3.703217e+00
std    1.425096e+00
min    1.000000e+00
25%    3.000000e+00
50%    4.000000e+00
75%    4.000000e+00
max    2.000000e+01

Primeiras 5 linhas:    NU_INSCRICAO  NU_ANO  TP_FAIXA_ETARIA TP_SEXO  TP_ESTADO_CIVIL  \
0  210062064233    2024                5       F                1
1  210062064234    2024               11       F                1
2  210062064235    2024               11       F                1
3  210062064236    2024                3       F                1
4  210062064237    2024               16       M                3

   TP_COR_RACA  TP_NACIONALIDADE  TP_ST_CONCLUSAO  TP_ANO_CONCLUIU  TP_ENSINO  \
0            1                 1                1                3        NaN
1            1                 1                1               10        NaN
2            1                 1                1                9        NaN
3            3                 1                2                0        1.0
4            1                 1                1               18        NaN

   ...  Q014  Q015 Q016  Q017 Q018 Q019 Q020 Q021 Q022  Q023
0  ...     A     B    B     B    D    A    B    B    E     A
1  ...     A     A    A     A    B    A    B    A    C     A
2  ...     A     B    B     B    D    B    B    A    D     A
3  ...     A     B    A     A    A    A    B    A    D     A
4  ...     A     A    A     A    B    A    B    A    B     A

[5 rows x 38 columns]

In [48]:
#dicionario colunas
novo_nome_colunas = {
    'NU_INSCRICAO': 'inscricao',
    'NU_ANO': 'ano',
    'TP_FAIXA_ETARIA': 'faixa_etaria',
    'TP_SEXO': 'sexo',
    'TP_ESTADO_CIVIL': 'estado_civil',
    'TP_COR_RACA': 'cor_raca',
    'TP_NACIONALIDADE': 'nacionalidade',
    'TP_ST_CONCLUSAO': 'status_conclusao',
    'TP_ANO_CONCLUIU': 'ano_conclusao',
    'TP_ENSINO': 'tipo_ensino',
    'IN_TREINEIRO': 'treineiro',
    'CO_MUNICIPIO_PROVA': 'cod_municipio_prova',
    'NO_MUNICIPIO_PROVA': 'municipio_prova',
    'CO_UF_PROVA': 'cod_uf_prova',
    'SG_UF_PROVA': 'uf_prova',
    'Q001': 'esc_mae',
    'Q002': 'esc_pai',
    'Q003': 'trab_mae',
    'Q004': 'trab_pai',
    'Q005': 'pessoas_residencia',
    'Q006': 'possui_renda',
    'Q007': 'renda_mensal_familiar',
    'Q008': 'contrata_servico_domestico',
    'Q009': 'tem_banheiro',
    'Q010': 'tem_quarto',
    'Q011': 'tem_carro',
    'Q012': 'tem_motocicleta',
    'Q013': 'tem_geladeira',
    'Q014': 'tem_freezer',
    'Q015': 'tem_maquina_de_lavar',
    'Q016': 'tem_micro_ondas',
    'Q017': 'tem_aspirador_de_po',
    'Q018': 'tem_tv',
    'Q019': 'tem_tv_por_assinatura',
    'Q020': 'tem_internet_wifi',
    'Q021': 'tem_computador_notebook',
    'Q022': 'tem_celular',
    'Q023': 'tipo_escola'
}

colunas_renomeadas = [
    'inscricao', 'ano', 'faixa_etaria', 'sexo', 'estado_civil', 'cor_raca', 'nacionalidade',
    'status_conclusao', 'ano_conclusao', 'tipo_ensino', 'treineiro', 'cod_municipio_prova',
    'municipio_prova', 'cod_uf_prova', 'uf_prova', 'esc_mae', 'esc_pai', 'trab_mae', 'trab_pai',
    'pessoas_residencia', 'possui_renda', 'renda_mensal_familiar', 'contrata_servico_domestico',
    'tem_banheiro', 'tem_quarto', 'tem_carro', 'tem_motocicleta', 'tem_geladeira', 'tem_freezer',
    'tem_maquina_de_lavar', 'tem_micro_ondas', 'tem_aspirador_de_po', 'tem_tv',
    'tem_tv_por_assinatura', 'tem_internet_wifi', 'tem_computador_notebook', 'tem_celular',
    'tipo_escola'
]

#renomear colunas
df = df.rename(columns=novo_nome_colunas)
df.head()

,inscricao,ano,faixa_etaria,sexo,estado_civil,cor_raca,nacionalidade,status_conclusao,ano_conclusao,tipo_ensino,...,tem_freezer,tem_maquina_de_lavar,tem_micro_ondas,tem_aspirador_de_po,tem_tv,tem_tv_por_assinatura,tem_internet_wifi,tem_computador_notebook,tem_celular,tipo_escola
0,210062064233,2024,5,F,1,1,1,1,3,NaN,...,A,B,B,B,D,A,B,B,E,A
1,210062064234,2024,11,F,1,1,1,1,10,NaN,...,A,A,A,A,B,A,B,A,C,A
2,210062064235,2024,11,F,1,1,1,1,9,NaN,...,A,B,B,B,D,B,B,A,D,A
3,210062064236,2024,3,F,1,3,1,2,0,1.0,...,A,B,A,A,A,A,B,A,D,A
4,210062064237,2024,16,M,3,1,1,1,18,NaN,...,A,A,A,A,B,A,B,A,B,A

In [51]:
#filtrar participantes da paraíba
df_pb_enem_2024 = df[df["uf_prova"] == "PB"]

#selecionar colunas de interesse
df_pb_enem_2024 = df_pb_enem_2024[colunas_renomeadas]
df_pb_enem_2024.head()

,inscricao,ano,faixa_etaria,sexo,estado_civil,cor_raca,nacionalidade,status_conclusao,ano_conclusao,tipo_ensino,...,tem_freezer,tem_maquina_de_lavar,tem_micro_ondas,tem_aspirador_de_po,tem_tv,tem_tv_por_assinatura,tem_internet_wifi,tem_computador_notebook,tem_celular,tipo_escola
79,210062064430,2024,12,F,2,5,1,1,14,NaN,...,A,A,A,A,B,A,B,A,C,A
285,210062064690,2024,5,M,1,4,1,1,0,NaN,...,A,B,A,A,B,A,B,B,C,A
492,210062065010,2024,9,M,1,2,1,1,6,NaN,...,A,A,A,A,B,A,B,A,D,A
645,210062065232,2024,3,M,1,3,1,1,1,NaN,...,A,B,B,B,C,A,B,D,E,D
646,210062065233,2024,19,F,3,3,1,4,0,NaN,...,A,B,B,B,B,A,B,A,B,A

In [52]:
#tratamento de valores ausentes
# Preenche objetos com string padrão
for col in df_pb_enem_2024.select_dtypes(include='object').columns:
    df_pb_enem_2024[col] = df_pb_enem_2024[col].fillna('Não informado')

# Preenche numéricos com mediana
for col in df_pb_enem_2024.select_dtypes(exclude='object').columns:
    df_pb_enem_2024[col] = df_pb_enem_2024[col].fillna(df_pb_enem_2024[col].median())

df_pb_enem_2024.head()

,inscricao,ano,faixa_etaria,sexo,estado_civil,cor_raca,nacionalidade,status_conclusao,ano_conclusao,tipo_ensino,...,tem_freezer,tem_maquina_de_lavar,tem_micro_ondas,tem_aspirador_de_po,tem_tv,tem_tv_por_assinatura,tem_internet_wifi,tem_computador_notebook,tem_celular,tipo_escola
79,210062064430,2024,12,F,2,5,1,1,14,1.0,...,A,A,A,A,B,A,B,A,C,A
285,210062064690,2024,5,M,1,4,1,1,0,1.0,...,A,B,A,A,B,A,B,B,C,A
492,210062065010,2024,9,M,1,2,1,1,6,1.0,...,A,A,A,A,B,A,B,A,D,A
645,210062065232,2024,3,M,1,3,1,1,1,1.0,...,A,B,B,B,C,A,B,D,E,D
646,210062065233,2024,19,F,3,3,1,4,0,1.0,...,A,B,B,B,B,A,B,A,B,A

In [55]:
#salvar o csv tratado
df_pb_enem_2024.to_csv("enem_pb_2024_tratado.csv", index=False)
print("Arquivo salvo com sucesso!")

Arquivo salvo com sucesso!